import 'dart:async';
import 'package:build/build.dart';

Builder dummyBuilder(BuilderOptions options) => DummyBuilder();

class DummyBuilder implements Builder {
  @override
  final Map<String, List<String>> buildExtensions = const {
    '.dart': ['.dummy'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    await buildStep.writeAsString(
      buildStep.inputId.changeExtension('.dummy'),
      '// Generated by dummyBuilder',
    );
  }
}
