name: CI

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        run: |
          bash scripts/install_flutter.sh
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze
